// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ctjjwxhwtqtacfhminye.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0amp3eGh3dHF0YWNmaG1pbnllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzExMDMzMjMsImV4cCI6MjA0NjY3OTMyM30.WqjFYof-PgDFcl7XD4-QZGgyyB3JBJyWG4pk6wpMW4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);